server:
  port: 7901
spring:
  application:
    name: ConsumerUser
  activemq:
    broker-url: tcp://192.168.13.18:61616
    in-memory: true
    user: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/