logging:
  level:
    java:
      sql:
        Connection: info
        Statement: info
    org:
      springframework:
        web: info
      apache: 
        commons: 
          httpclient: error

spring:

  rabbitmq:
    #standalone mode config
    host: 106.54.193.61
    port: 5672
    password: admin
    username: admin
    virtual-host: /
    cache:
      channel:
        size: 10
    listener:
      simple:
        acknowledge-mode: manual


 
  