logging:
  level:
    java:
      sql:
        Connection: info
        Statement: info
    org:
      springframework:
        web: info
      apache: 
        commons: 
          httpclient: error
        http: error




 
  